name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build solution
      run: dotnet build
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
